### PR TITLE
[Reviewer: Rob] Fix possible deadlock in quiescing

### LINKED ISSUE #1351: Possible deadlock - worker thread and quiescing thread can take connection manager lock and transport lock in different orders
Split out from https://github.com/Metaswitch/sprout/issues/1325 to keep issues separate.

### PR DESCRIPTION
**Pull request by johadalin**
This merges the quiescing thread with the PJSIP transport thread. 
This should avoid a possible deadlock condition. 

The relocation of stack.cpp:L714/753 is to fix crashes that were seen on stopping or quiescing sprout. 

These changes have been tested on a live deployment, and quiescing shows no crashing or locking.
Once https://github.com/Metaswitch/sprout/pull/1344 is merged, it may be worth adding in CHECK_PJ_TRANSPORT_THREAD() before running the quiesce calls, to ensure we are being safe.

Will fix #1351

### CODE REVIEW

**Comment by johadalin** [comment]
Closing, as should be against fixes branch, not dev

**Comment by johadalin** [comment]
I've added CHECK_PJ_TRANSPORT_THREAD at the start of the pjsip_tread_function. 
@rkd-msw are you happy where i've put it? 

If so, i'll merge this into dev and close #1351

**Comment by rkd-msw** [comment]
Sadly I'm not - `pjsip_thread_func` is by definition always on the PJSIP transport thread (it *is* the PJSIP transport thread). Can you put `CHECK_PJ_TRANSPORT_THREAD` at the top of the ConnectionTracker methods instead?

**Comment by johadalin** [comment]
Removed the CHECK_PJ_TRANSPORT_THREAD from the previous location, and added it in place of the lock in connection tracker methods. 

Tested on a live deployment by adding a debug log alongside the see when the methods were called, and ensuring that the CHECK did not raise any errors when in normal use, and when stopped or quiesced.

Does this now look good to merge in?

**Comment by rkd-msw** [comment]
Can you also remove the lock from the header file (https://github.com/Metaswitch/sprout/blob/dev/include/connection_tracker.h#L87)? Then good to merge.

**Pull request merged**
