### PR TITLE
[Reviewer: RKD] Allow list headers to have a trailing comma

### PR DESCRIPTION
**Pull request by Neil-Bruce**
Rob,

Could you review this change to the tests for the Supported: header with a trailing comma?  Passing direct to you since you've looked at this already - hope that's OK.

Note that I have not run the live tests against this fix as it seems fairly minor.  Let me know if you think I need to run them before releasing.

Neil

### CODE REVIEW

**Comment by rkd-msw** [comment]
Looks good, but see https://github.com/Metaswitch/pjsip-upstream/pull/61#issuecomment-283387532 for some more suggested tests.

**Comment by rkd-msw** [comment]
If you add more testcases, it might be best to parameterise this, e.g.:

**Comment by rkd-msw** [comment]
```
TEST_F(CommonProcessingTest, CommasInSupportedHeader)
{
  // Tests that a trailing comma on request is accepted.
  pjsip_tx_data* tdata;
  pjsip_endpt_register_module(stack_data.endpt, &mod_ok);

  std::vector<std::string> headers = {"Supported: timer,", "Supported: \n  ,,,,"};

  for (std::string h: headers) {
    SCOPED_TRACE(h);
    // Inject a request with a trailing comma.
    Message msg1;
    msg1._extra = h;
    inject_msg(msg1.get_request(), _tp);

    // Expect a response from mod_ok.
    ASSERT_EQ(1, txdata_count());

    tdata = current_txdata();
    RespMatcher r1(200);
    r1.matches(tdata->msg);

    free_txdata();
  }
  pjsip_endpt_unregister_module(stack_data.endpt, &mod_ok);
}
```

**Comment by Neil-Bruce** [comment]
I tried running multiple tests in a single test case before.  The first one runs OK but all subsequent cases get a "503 Service Unavailable" error instead of the expected 200 OK.  Couldn't get it to work before and the same thing happens with your code above.  I'll try and work it out but do you have any idea why?

**Comment by Neil-Bruce** [comment]
Ah, I think it is the load monitor running out of tokens.

**Comment by Neil-Bruce** [comment]
Extra test cases added as above but with a new load monitor to allow all tests to complete.

**Comment by rkd-msw** [comment]
👍

**Pull request merged**
