### PR TITLE
[Reviewer: Ellie] Remove port from the default Sproutlet URIs

### PR DESCRIPTION
**Pull request by richardwhiuk**
As discussed, we think this is the right change.

### CODE REVIEW

**Comment by pdavies** [comment]
@eleanor-merry @rkd-msw Does this need to wait until @richardwhiuk is back from holiday, or can I merge?

**Comment by eleanor-merry** [comment]
I say merge it

**Comment by rkd-msw** [comment]
@eleanor-merry , @richardwhiuk - we've hit test failures after taking this, which are because you need corresponding changes in Homestead. See https://github.com/Metaswitch/homestead/blob/dev/debian/homestead.init.d#L96-L98. Do you want me to raise an issue?

@graemerobertson

**Comment by eleanor-merry** [comment]
I've hopefully made the change in https://github.com/Metaswitch/homestead/pull/463/files - I don't think there needs to be a separate issue.

**Pull request merged**
