### PR TITLE
[Reviewer: Adam] Challenge Emergency Registrations

### PR DESCRIPTION
**Pull request by sebrexmetaswitch**
Emergency Registrations should be challenged, just as normal registrations are.
If the UE fails the challenge, it should make an emergency call without a registration.

This PR removes the code and SAS log that special-cased the emergency registration, and updates the Authentication Sproutlet's UTs to reflect the new behaviour.

Also adds a new SAS log to indicate that a registration is an emergency one (if it is) as suggested by Adam here: https://github.com/Metaswitch/sprout/pull/2154 (which I've closed as SDM was merged in the meantime)

### CODE REVIEW

**Comment by sebrexmetaswitch** [comment]
Linked issue is: https://github.com/Metaswitch/clearwater-issues/issues/2884

**Comment by sebrexmetaswitch** [comment]
Setting Adam as reviewer as he already reviewed these changes on the other PR

**Comment by johadalin** [comment]
Yep, all looks good to me. Had a look over the linked PRs as well, and it all seems fine.

What are we planning to do in the way of testing here though? as it feels like a fairly important thing to verify.

**Comment by sebrexmetaswitch** [comment]
Sorry, I actually meant that I was just writing that you'd reviewed it already, but good to see that it's still OK :)

Testing has been done manually and in our live-tests. I'm just waiting for a pipeline to pass at the moment

**Pull request merged**
