### PR TITLE
[Reviewer: Ellie] Bracket the IPv6 address before using it (ready to merge)

### LINKED ISSUE #1029: IPv6 is generally broken for the S-CSCF sproutlet
If the sprout_hostname is an IPv6 address then the S-CSCF plugin fails to load as the BGCF URI is invalid 

Debug scscfsproutlet.cpp:99:   BGCF URI           = sip:bgcf.[::1]:5054;transport=TCP
Error scscfsproutlet.cpp:125: Invalid BGCF URI sip:bgcf.[::1]:5054;transport=TCP

### PR DESCRIPTION
**Pull request by rkd-msw**
Fixes #1029. With this change, and the following config:

```
$ cat /etc/clearwater/local_config
local_ip=fd5f:5d21:845:1402:407e:aa42:6989:4d58
public_ip=fd5f:5d21:845:1402:407e:aa42:6989:4d58
public_hostname=sprout-1
etcd_cluster="fd5f:5d21:845:1402:407e:aa42:6989:4d58"
```

Sprout loads without error logs and the S-CSCF sproutlet handles requests I send it (using SIPp). I don't have a full IPv6 test rig, so haven't made an end-to-end call.

### CODE REVIEW

**Comment by eleanor-merry** [comment]
This change looks good, but I don't think it fully fixes #1029. What if the hostname values are IPv6 addresses?

**Comment by rkd-msw** [comment]
I think sprout_hostname (and the host part of scscf_uri) has to be a hostname and we should document that. Note that it only works by chance as an IPv4 address:

```
13-08-2015 11:26:38.157 UTC Debug scscfsproutlet.cpp:111: Creating S-CSCF Sproutlet
13-08-2015 11:26:38.157 UTC Debug scscfsproutlet.cpp:112:   S-CSCF cluster URI = sip:127.0.0.1:5054;transport=TCP
13-08-2015 11:26:38.157 UTC Debug scscfsproutlet.cpp:113:   S-CSCF node URI    = sip:10.0.246.227:5054
13-08-2015 11:26:38.157 UTC Debug scscfsproutlet.cpp:114:   I-CSCF URI         = sip:127.0.0.1:5052;transport=TCP
13-08-2015 11:26:38.157 UTC Debug scscfsproutlet.cpp:115:   BGCF URI           = sip:bgcf.127.0.0.1:5054;transport=TCP
```

`sip:bgcf.127.0.0.1:5054` is not a normal-looking URI.

**Comment by rkd-msw** [comment]
Hmm. Maybe I could do `sip:bgcf@[ip]` instead which solves that problem.

**Comment by rkd-msw** [comment]
Fixed, re-review?

**Comment by eleanor-merry** [comment]
Looks good - what testing have you done?

**Comment by rkd-msw** [comment]
@eleanor-merry, I'm going to set sprout_hostname and scscf_uri to use an IPv6 address and confirm that:

- Sprout loads without error logs
- the S-CSCF sproutlet handles requests I send it
- the S-CSCF Sproutlet can pass requests on to the BGCF.

Good enough?

**Comment by rkd-msw** [comment]
I've done the above testing (albeit checking that the I-CSCF Sproutlet, not tyhe S-CSCF Sproutlet, could route to the BGCF - that was easier to test):

```
15-09-2015 10:23:50.097 UTC Info icscfsproutlet.cpp:862: Routing to BGCF sip:bgcf@[::1]:5054
15-09-2015 10:23:50.097 UTC Debug sproutletproxy.cpp:1218: Sproutlet send_request 0x7f63d800a1c0
15-09-2015 10:23:50.097 UTC Verbose sproutletproxy.cpp:1254: icscf-0x7f63d800f300 sending Request msg INVITE/cseq=1 (tdta0x7f63d8009bb0) on fork 0
15-09-2015 10:23:50.097 UTC Debug sproutletproxy.cpp:1606: Processing actions from sproutlet - 0 responses, 1 requests
15-09-2015 10:23:50.097 UTC Debug sproutletproxy.cpp:1641: Processing request 0x7f63d8009c58, fork = 0
15-09-2015 10:23:50.097 UTC Debug sproutletproxy.cpp:1759: icscf-0x7f63d800f300 transmitting request on fork 0
15-09-2015 10:23:50.097 UTC Debug sproutletproxy.cpp:1773: icscf-0x7f63d800f300 store reference to non-ACK request Request msg INVITE/cseq=1 (tdta0x7f63d8009bb0) on fork 0
15-09-2015 10:23:50.097 UTC Debug sproutletproxy.cpp:1598: Removing message 0x7f63d800a1c0 => txdata 0x7f63d8009c58 mapping
15-09-2015 10:23:50.097 UTC Debug sproutletproxy.cpp:102: Find target Sproutlet for request
15-09-2015 10:23:50.097 UTC Debug sproutletproxy.cpp:136: Found next routable URI: sip:bgcf@[::1]:5054;lr
15-09-2015 10:23:50.097 UTC Debug sproutletproxy.cpp:261: Found user - bgcf
15-09-2015 10:23:50.097 UTC Verbose sproutletproxy.cpp:1022: Created Sproutlet bgcf-0x7f63d8033880 for Request msg INVITE/cseq=1 (tdta0x7f63d8009bb0)
```

Ready to merge at end of code freeze.

**Pull request merged**
