### PR TITLE
Move MockSproutletProxy etc to make them generally available

### PR DESCRIPTION
**Pull request by dimbleby**
On the other hand I have a pull request that will make its way across to you in due course to re-introduce these mocks in cpp_common, where they can be used by sproutlet unit tests too.

### CODE REVIEW

**Comment by dimbleby** [comment]
Decided that these mocks did belong in this repository rather than in cpp-common, but put them in their own header files so as to make them generally available.

Includes mocks for methods introduced at #1233, so likely doesn't make sense to take this before that.

**Comment by bossmc** [comment]
@AlexHockey - Continuation of the work in #1233 which you're reviewing.  I think this change is fine once you've reviewed that.   Passing to you to click the big green button when ready.

**Comment by rkd-msw** [comment]
Is https://github.com/Metaswitch/clearwater-app-servers/tree/b57cc36bf11ef1c2035777144051158d5a0aa0cf a sensible place for them?

**Comment by bossmc** [comment]
Nope, that repository hold the application server API which this isn't.  I question whether that repo is adding much or making life more difficult...

**Comment by AlexHockey** [comment]
Not sure how this builds given `sproutletproxy_test.cpp` doesn't include the new headers...

**Comment by mbt-msw** [comment]
It compiles because MockSproutlet and friends are not used in the existing code.  They are, however, useful for other sproutlets to use in their unit tests, which is why they're being retained in their own headers.

**Comment by AlexHockey** [comment]
Cool.

**Pull request merged**
