### PR TITLE
[Review AJH] Allow for minimal Accept-Contact header

### PR DESCRIPTION
**Pull request by steelyvoid**
Fixes a problem whereby the (valid) header "Accept-Contact: *" was being rejected by parse_hdr_accept_contact.

Tested live using an OPTIONS message with the above header.  Custom header UTs pass.  I decided not to write a new UT to cover this case - let me know if you think thats the wrong call.

### CODE REVIEW

**Comment by AlexHockey** [comment]
Looks good to me. Would a unit test be hard to add? Regression tests are generally a good thing.

**Comment by steelyvoid** [comment]
OK.  I wasn't sure whether it was worth the increase in UT execution time, but I'll add one if you prefer

**Comment by AlexHockey** [comment]
Thanks Steve. FYI we generally don't worry too much about execution time of the UTs (unless the UT is unusual in some way, which this isn't).

**Comment by rkd-msw** [comment]
I think I'd say that we don't worry about the **aggregate** execution time of the UTs - an individual UT that took a second to run would be frowned upon, I think (but this UT will be milliseconds at most),

**Pull request merged**
